# This is an appspec.yml template file for use with AWS CodeDeploy.
version: 0.0
os: linux
files:
  - source: ./deploy/nfe-servico.conf
    destination: /etc/init/
  - source: /
    destination: /srv/src/
hooks:
  AfterInstall:
    - location: ./deploy/after-install.sh
      runas: root
  ApplicationStart:
    - location: ./deploy/start.sh
      runas: root
  ApplicationStop:
    - location: ./deploy/stop.sh
      runas: root
  ValidateService:
    - location: ./deploy/validate.sh
      runas: root
      timeout: 60
